name: CI Pipeline

on:
  push:
    branches: [ develop, feature/** ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Skip requirements.txt entirely for now
        echo "Skipping requirements.txt installation"
        
    - name: Run tests
      run: |
        python -m unittest discover -v
